import datetime
from feedgen.feed import FeedGenerator

def generate_kabir_feed():
    # THE DOHA LIBRARY
    couplets = [
        {"couplet_hindi": "काल करे सो आज कर, आज करे सो अब । पल में प्रलय होएगी, बहुरि करेगा कब ॥", "explanation": "Do tomorrow's work today, and today's work right now.", "translation": "Tomorrow's work do today, today's work now. If the moment is lost, how will the work be done?"},
        {"couplet_hindi": "बुरा जो देखन मैं चला, बुरा न मिलिया कोय । जो दिल खोजा आपना, मुझसे बुरा न कोय ॥", "explanation": "I searched the world for bad people but found none. When I looked inside my own heart, I realized I am the worst of all.", "translation": "I went searching for the wicked, but found no one. When I searched my own heart, I found no one worse than me."},
        {"couplet_hindi": "दुख में सुमिरन सब करे, सुख में करै न कोय । जो सुख में सुमिरन करे, दुख काहे को होय ॥", "explanation": "Everyone remembers God in sorrow, no one remembers in joy. If one remembers God in joy, why would sorrow ever come?", "translation": "In sorrow everyone remembers Him, in joy no one does. If one remembers Him in joy, why would sorrow come?"},
        {"couplet_hindi": "गुरु गोविंद दोऊ खड़े, काके लागूं पाँय । बलिहारी गुरु आपने, गोविंद दियो बताय ॥", "explanation": "Both Guru and God are standing before me, whose feet should I touch first? I bow to my Guru.", "translation": "Guru and God both are standing, whose feet should I touch? I surrender to my Guru who introduced me to God."},
        {"couplet_hindi": "माटी कहे कुम्हार से, तु क्या रौंदे मोय । एक दिन ऐसा आएगा, मैं रौंदूगी तोय ॥", "explanation": "The clay says to the potter, 'Why do you trample me? A day will come when I will trample you.'", "translation": "Clay says to the potter, why do you knead me? A day will come when I will knead you."},
        {"couplet_hindi": "ऐसी बानी बोलिए, मन का आपा खोय । औरन को शीतल करे, आपहुं शीतल होय ॥", "explanation": "Speak such words that you lose your ego. Words that cool the listener and cool yourself.", "translation": "Speak such words that you lose your ego. It cools others and cools yourself too."},
        {"couplet_hindi": "पोथी पढ़ि पढ़ि जग मुआ, पंडित भया न कोय । ढाई आखर प्रेम का, पढ़े सो पंडित होय ॥", "explanation": "Reading books, the world died, no one became wise. One who reads the two and a half letters of 'Love' becomes wise.", "translation": "Reading books the world died, none became a scholar. He who reads the two and a half letters of Love, becomes a scholar."},
        {"couplet_hindi": "बड़ा हुआ तो क्या हुआ, जैसे पेड़ खजूर । पंथी को छाया नहीं, फल लागे अति दूर ॥", "explanation": "What is the use of being big like a date tree? It gives no shade to travelers and its fruits are too high to reach.", "translation": "What if you are big, like the date palm tree. No shade for the traveler, and fruit grows too far."},
        {"couplet_hindi": "कबीरा गर्व ना कीजिये, काल गहे कर केश । ना जानों कहाँ मारिसी, क्या घर क्या परदेश ॥", "explanation": "Do not be proud; death has you by the hair. You know not where it will strike, whether at home or in a foreign land.", "translation": "Be not proud, death holds your hair. You know not where it strikes, at home or elsewhere."},
        {"couplet_hindi": "दुर्लभ मानुष जन्म है, देह न बारम्बार । तरुवर ज्यों पत्ती झड़े, बहुरि न लागे डार ॥", "explanation": "Human birth is rare; this body is not gained again and again. Like a leaf falls from a tree and never returns to the branch.", "translation": "Human life is rare, it comes not again. Like a fallen leaf that never returns to the branch."},
        {"couplet_hindi": "जग में बैरी कोई नहीं, जो मन शीतल होय । यह आपा तो डारि दे, दया करे सब कोय ॥", "explanation": "No one is your enemy if your mind is calm. If you drop your ego, everyone will show you compassion.", "translation": "No one is your foe if your mind is cool. Drop your ego, and the world will be kind to you."},
        {"couplet_hindi": "साईं से लगन लगाये रख, फल की इच्छा त्याग । जब समय आएगा तेरा, बदल जाएगा भाग ॥", "explanation": "Keep your devotion to the Lord and give up the desire for fruits. When your time comes, your fate will change.", "translation": "Stay devoted to the Lord, forget the reward. When the time is right, your luck will turn."},
        {"couplet_hindi": "सबै रसायन मैं किया, प्रेम समान न कोय । रंचक ही में तन तपे, कंचन सा तन होय ॥", "explanation": "I have tried all elixirs, but none is like Love. Even a little makes the body shine like pure gold.", "translation": "I tried all potions, but none like love. A tiny bit transforms the body into gold."},
        {"couplet_hindi": "कबीरा संगत साधु की, ज्यों गंधी की बास । जो कुछ गंधी दे नहीं, तो भी बास सुबास ॥", "explanation": "The company of a saint is like a perfume seller. Even if he gives you nothing, the fragrance stays with you.", "translation": "Company of a saint is like a perfumer. Even if he gives nothing, the scent remains."},
        {"couplet_hindi": "माली आवत देख के, कलियन करे पुकार । फूले-फूले चुन लिये, काल्हि हमारी बार ॥", "explanation": "Seeing the gardener coming, the buds cry out. He picked all the flowers today; tomorrow it will be our turn.", "translation": "Seeing the gardener, the buds cry: He picked the flowers today, tomorrow is our turn."},
        {"couplet_hindi": "चाह मिटी चिंता मिटी, मनवा बेपरवाह । जिसको कछू न चाहिए, वो साहन के साह ॥", "explanation": "Desire ended, worry ended, the mind became carefree. He who wants nothing is the king of kings.", "translation": "Desire and worry gone, the mind is free. He who wants nothing is the king of kings."},
        {"couplet_hindi": "जा घट प्रेम न संचरे, सो घट जान मसान । जैसे खाल लुहार की, सांस लेत बिनु प्रान ॥", "explanation": "A heart without love is like a cremation ground. Like the blacksmith's bellows, it breathes without life.", "translation": "A heart without love is a graveyard. It breathes like bellows, but has no life."},
        {"couplet_hindi": "कहता हूँ कहि जात हूँ, कहूँ जो ठोक बजाय । कुआँ पास है आपणे, तू क्यों प्यासा जाय ॥", "explanation": "I say it again and again, and I say it with certainty. The well is near you; why do you remain thirsty?", "translation": "I tell you truly, the well is right here. Why do you still wander with thirst?"},
        {"couplet_hindi": "साधु शब्द समुद्र है, जामें रत्न अपार । मूरख भेद न जानहीं, ढूँढत फिरे किनार ॥", "explanation": "The words of a saint are an ocean filled with gems. Fools don't know the secret and look only on the shore.", "translation": "A saint's word is an ocean of gems. Fools know not the secret and stay on the shore."},
        {"couplet_hindi": "चिंता ऐसी डाकिनी, काटि कलेजा खाय । बैद बिचारा क्या करे, कहाँ तक दवा लगाय ॥", "explanation": "Worry is such a witch that she eats the heart. What can the poor doctor do? How far can medicine reach?", "translation": "Worry is a witch that eats the heart. What can a doctor do? Medicine cannot reach it."},
        {"couplet_hindi": "तन को जोगी सब करें, मन को बिरला कोय । सहजै सब सिधि पाइए, जो मन जोगी होय ॥", "explanation": "Everyone makes the body a yogi, but rarely anyone makes the mind one. All success is easy if the mind becomes a yogi.", "translation": "Many discipline the body, few the mind. All is achieved if the mind is disciplined."},
        {"couplet_hindi": "हाड़ जलै ज्यों लाकड़ी, केस जलै ज्यों घास । सब जग जलता देखि करि, भये कबीर उदास ॥", "explanation": "Bones burn like wood, hair burns like grass. Seeing the whole world burning (in worldliness), Kabir became sad.", "translation": "Bones burn like wood, hair like grass. Seeing the world burn, Kabir is saddened."},
        {"couplet_hindi": "कबीर लहरि समंद की, मोती बिखरे आइ । बगुला भेद न जानई, हंसा चुनि-चुनि खाइ ॥", "explanation": "The waves of the ocean bring pearls to the shore. The crane doesn't know their value, but the swan picks them up.", "translation": "Waves bring pearls to the shore. The crane knows not, the swan picks them up."},
        {"couplet_hindi": "पाहन पूजे हरि मिले, तो मैं पूजूं पहार । ताते यह चाकी भली, पीस खाय संसार ॥", "explanation": "If worshipping a stone finds God, I'll worship a mountain. Better is the grinding stone that feeds the world.", "translation": "If stones find God, I'll worship a hill. Better is the millstone that feeds the world."},
        {"couplet_hindi": "कबीर आपा मेटि करि, हरि भजि तजि अभिमान । जिहि घट दया न संचरे, सो घट जान मसान ॥", "explanation": "Kabir, erase your ego and worship God, leaving pride. A heart without compassion is a cremation ground.", "translation": "Kabir, kill the ego and pray. A heart without mercy is a graveyard."},
        {"couplet_hindi": "जाको राखे साइयां, मारि सके न कोय । बाल न बांका करि सके, जो जग बैरी होय ॥", "explanation": "He whom God protects, no one can kill. Not a hair can be harmed, even if the whole world is an enemy.", "translation": "Whom God protects, none can slay. Not a hair is harmed if the world is a foe."},
        {"couplet_hindi": "बोली एक अनमोल है, जो कोई बोले जानि । हिये तराजू तौलि के, तब मुख बाहर आनि ॥", "explanation": "A word is priceless if you know how to speak. Weigh it in the scale of your heart before it leaves your mouth.", "translation": "A word is priceless. Weigh it in your heart's scale before you speak."},
        {"couplet_hindi": "कबीरा संगत साधु की, कदे न निरफल होय । लोहा कंचन होत है, जो पारस परसे कोय ॥", "explanation": "Company with a saint never goes in vain. Just as iron turns to gold when it touches the philosopher's stone.", "translation": "Company of a saint is never wasted. Iron turns to gold by the touch of the stone."},
        {"couplet_hindi": "लूटि सके तो लूटि ले, राम नाम की लूटि । पाछे ही पछताओगे, प्राण जाहिंगे छूटि ॥", "explanation": "Gather the name of God while you can. You will regret it later when life leaves your body.", "translation": "Gather God's name now. You will regret it when life departs."},
        {"couplet_hindi": "कबीर सोया क्या करे, उठि न भजे भगवान । जम जब घर में आइसी, तब नहिं जपे कमान ॥", "explanation": "Kabir, why do you sleep? Wake up and pray. When Death enters your house, you won't be able to pray.", "translation": "Kabir, why sleep? Wake up and pray. When Death arrives, you cannot pray."},
        {"couplet_hindi": "कबीरा गरब न कीजिये, ऊँचा देखि आवास । काल परों भुईं लेटना, ऊपर जमसी घास ॥", "explanation": "Do not be proud of your high mansion. Tomorrow you will lie in the dust, and grass will grow over you.", "translation": "Be not proud of your high home. Tomorrow you lie in dust, covered in grass."},
        {"couplet_hindi": "रात गंवाई सोय के, दिवस गंवाया खाय । हीरा जनम अमोल था, कौड़ी बदले जाय ॥", "explanation": "The night was lost in sleep, the day in eating. This diamond-like life was priceless, but it's going for a penny.", "translation": "Night lost to sleep, day to food. This priceless life is sold for a penny."},
        {"couplet_hindi": "कबीरा तेलिन के बैल को, घर ही कोस पचास । सवेरे उठा फिर वहीं, साँझ हुई तो पास ॥", "explanation": "The oilman's bull travels fifty miles but stays in the same place. He starts and ends in the same spot.", "translation": "The oilman's bull walks miles but stays put. He ends where he began."},
        {"couplet_hindi": "फल कारन सेवा करे, तजे न मन से काम । कह कबीर सेवक नहीं, चहै चोगुना दाम ॥", "explanation": "One who serves for reward and doesn't give up desire is not a servant; he wants four times the price.", "translation": "He who serves for reward is no servant; he only wants a higher price."},
        {"couplet_hindi": "जो तोको कांटा बुवै, ताहि बोय तू फूल । तोको फूल के फूल हैं, बाको है तिरशूल ॥", "explanation": "If someone sows thorns for you, sow flowers for them. You will get flowers, and they will get thorns.", "translation": "If one sows thorns, sow flowers. You get flowers, they get thorns."},
        {"couplet_hindi": "कबीर दर्शन साधु के, बड़े भाग से होय । जो कछु किया सोई मिला, अब कछु और न कोय ॥", "explanation": "Meeting a saint happens through great fortune. What you did is what you got; there is nothing else now.", "translation": "Meeting a saint is great luck. You get what you gave; nothing more remains."},
        {"couplet_hindi": "साधु ऐसा चाहिये, जैसा सूप सुभाय । सार-सार को गहि रहै, थोथा देइ उड़ाय ॥", "explanation": "A saint should be like a winnowing basket. It keeps the essence and blows away the hollow chaff.", "translation": "A saint should be like a winnowing fan. Keep the truth, blow away the false."},
        {"couplet_hindi": "माला फेरत जुग भया, फिरा न मन का फेर । कर का मनका डारि दे, मन का मनका फेर ॥", "explanation": "A whole age passed turning beads, but the mind didn't turn. Drop the wooden beads and turn the beads of the heart.", "translation": "Years passed turning beads, the mind didn't change. Drop the beads, turn the heart."},
        {"couplet_hindi": "कबीरा खड़ा बाज़ार में, मांगे सबकी खैर । ना काहू से दोस्ती, ना काहू से बैर ॥", "explanation": "Kabir stands in the market, wishing well for all. Neither friendship with anyone, nor enmity with any.", "translation": "Kabir stands in the market, wishing all well. No friends, no foes."},
        {"couplet_hindi": "कबीर मानुष जन्म दुर्लभ है, देह न बारम्बार । तरुवर से पत्ता झड़ गया, बहुरि न लागे डार ॥", "explanation": "Human life is rare; this body comes but once. Once a leaf falls from a tree, it never rejoins the branch.", "translation": "Life is rare, the body comes once. A fallen leaf never returns to the branch."},
        {"couplet_hindi": "निंदक नियरे राखिए, ऑंगन कुटी छवाय । बिन पानी, साबुन बिना, निर्मल करे सुभाय ॥", "explanation": "Keep your critics close. Without water or soap, they cleanse your character.", "translation": "Keep critics close. They clean your nature without soap or water."},
        {"couplet_hindi": "ज्यों नैनों में पुतली, त्यों मालिक घट माहिं । मूरख लोग न जानहीं, बाहर ढूँढन जाहिं ॥", "explanation": "As the pupil is in the eye, the Lord is within the body. Fools know it not and search outside.", "translation": "As the pupil is in the eye, God is within. Fools seek Him outside."},
        {"couplet_hindi": "प्रेम पियाला जो पिये, शीश दक्षिणा देय । लोभी शीश न दे सके, नाम प्रेम का लेय ॥", "explanation": "He who drinks the cup of love gives his head as a gift. The greedy cannot give their head but still speak of love.", "translation": "He who drinks love's cup gives his life. The greedy cannot, yet they speak of love."},
        {"couplet_hindi": "कबीर सोई पीर है, जो जाने पर पीर । जो पर पीर न जानई, सो काफिर बेपीर ॥", "explanation": "He is a true saint who knows others' pain. He who does not is heartless.", "translation": "A true saint feels others' pain. He who doesn't is without a soul."},
        {"couplet_hindi": "पोथी पढ़ि पढ़ि जग मुआ, पंडित भया न कोय । ढाई आखर प्रेम का, पढ़े सो पंडित होय ॥", "explanation": "Reading books the world died, no one became wise. He who reads 'Love' becomes wise.", "translation": "Books didn't make the world wise. He who reads 'Love' is truly wise."},
        {"couplet_hindi": "धीरे-धीरे रे मना, धीरे सब कुछ होय । माली सींचे सौ घड़ा, ॠतु आए फल होय ॥", "explanation": "Slowly, mind, everything happens slowly. The gardener waters much, but fruit comes in its season.", "translation": "Slowly, my mind, all happens slowly. Rain or shine, fruit comes in its season."},
        {"couplet_hindi": "बड़ा हुआ तो क्या हुआ, जैसे पेड़ खजूर । पंथी को छाया नहीं, फल लागे अति दूर ॥", "explanation": "What is the use of being big like a date tree? No shade for travelers, and fruit is too high.", "translation": "Bigness like a date tree is useless. No shade, and fruit is out of reach."},
        {"couplet_hindi": "साधु भूखा भाव का, धन का भूखा नाहिं । जो धन का भूखा फिरे, सो तो साधु नाहिं ॥", "explanation": "A saint hungers for love, not wealth. He who seeks wealth is no saint.", "translation": "A saint wants love, not money. A money-seeker is no saint."},
        {"couplet_hindi": "जब मैं था तब हरि नहीं, अब हरि हैं मैं नाहिं । प्रेम गली अति सांकरी, तामें दो न समाहिं ॥", "explanation": "When I (ego) was there, God was not. Now God is there, and I am not. The path of love is too narrow for two.", "translation": "When I was, God was not. Now God is, I am not. Love's path is too narrow for two."},
        {"couplet_hindi": "माटी कहे कुम्हार से, तु क्या रौंदे मोय । एक दिन ऐसा आएगा, मैं रौंदूगी तोय ॥", "explanation": "Clay says to the potter: Why do you trample me? One day I will trample you.", "translation": "Clay tells the potter: You trample me now, but one day I will trample you."},
        {"couplet_hindi": "साईं इतना दीजिये, जा मे कुटुम समाय । मैं भी भूखा न रहूँ, साधु ना भूखा जाय ॥", "explanation": "Lord, give me enough to sustain my family. I shouldn't go hungry, nor should a guest.", "translation": "Lord, give me just enough for my family. No hunger for me or my guests."},
        {"couplet_hindi": "अति का भला न बोलना, अति की भली न चूप । अति का भला न बरसना, अति की भली न धूप ॥", "explanation": "Too much talk is bad, as is too much silence. Too much rain is bad, as is too much sun.", "translation": "Too much talk or silence is bad. Too much rain or sun is bad."},
        {"couplet_hindi": "कबीरा सूता क्या करे, जागी न जपे मुरार । एक दिन ऐसा सोवना, लंबे पाँव पसार ॥", "explanation": "Kabir, why sleep? Wake and pray. One day you will sleep forever with legs stretched out.", "translation": "Kabir, why sleep? Wake and pray. One day you will sleep for eternity."},
        {"couplet_hindi": "तिनका कबहुं ना निंदिये, जो पाँवन तर होय । कबहुं उड़ ऑंखिन पड़े, पीर घनेरी होय ॥", "explanation": "Never mock a tiny straw under your feet. If it flies into your eye, it hurts deeply.", "translation": "Mock not the straw underfoot. If it hits your eye, the pain is great."},
        {"couplet_hindi": "गुरु गोविंद दोऊ खड़े, काके लागूं पाँय । बलिहारी गुरु आपने, गोविंद दियो बताय ॥", "explanation": "Guru and God stand together; whose feet should I touch? I bow to the Guru who showed me God.", "translation": "Guru and God are here; I bow to the Guru who revealed God to me."},
        {"couplet_hindi": "हीरा वहाँ न खोलिये, जहाँ कुंजड़ी की हाट । सहजै गाँठि बाँधि के, लगिये अपनी बाट ॥", "explanation": "Don't show diamonds in a vegetable market. Tie your knot and go your way.", "translation": "Show not diamonds to vegetable sellers. Pack them and move on."},
        {"couplet_hindi": "जैसी प्रीति कुटुम्ब की, तैसी हरि सो होय । चला जाय वैकुण्ठ को, पल्ला न पकड़े कोय ॥", "explanation": "If your love for God was like your love for family, you would reach heaven easily.", "translation": "Love God like you love family, and heaven is yours."},
        {"couplet_hindi": "कबीर लहरि समंद की, मोती बिखरे आइ । बगुला भेद न जानई, हंसा चुनि-चुनि खाइ ॥", "explanation": "Ocean waves bring pearls. The crane knows not, the swan picks them up.", "translation": "Waves bring pearls. The crane is ignorant, the swan gathers them."},
        {"couplet_hindi": "जाति न पूछो साधु की, पूछ लीजिये ज्ञान । मोल करो तलवार का, पड़ा रहन दो म्यान ॥", "explanation": "Don't ask a saint's caste, ask for his wisdom. Price the sword, leave the sheath.", "translation": "Ask wisdom, not caste. Value the sword, not the sheath."},
        {"couplet_hindi": "जैसा अन्न वैसा मन, जैसा पानी वैसी बानी ।", "explanation": "As is the food, so is the mind. As is the water, so is the speech.", "translation": "Your mind follows your food. Your speech follows your water."},
        {"couplet_hindi": "एक ही साधे सब सधे, सब साधे सब जाय । माली सींचे मूल को, फूले फले अघाय ॥", "explanation": "Master one and master all. Try to master all and lose all. Water the root to get fruit.", "translation": "Master one to gain all. Water the root to flourish."},
        {"couplet_hindi": "मन के हारे हार है, मन के जीते जीत । कह कबीर हरि पाइए, मन ही की परतीत ॥", "explanation": "Defeat is in the mind, victory is in the mind. God is found through the faith of the mind.", "translation": "Victory and defeat are in the mind. God is found through faith."},
        {"couplet_hindi": "चिंता से चतुराई घटे, दुख से घटे शरीर । पाप से लक्ष्मी घटे, कह गए दास कबीर ॥", "explanation": "Worry reduces cleverness, sorrow weakens the body. Sin reduces wealth, says Kabir.", "translation": "Worry dulls the mind, sorrow hurts the body. Sin takes wealth away."},
        {"couplet_hindi": "बोली एक अनमोल है, जो कोई बोले जानि ।", "explanation": "Words are priceless if spoken with wisdom.", "translation": "Words have no price if spoken wisely."},
        {"couplet_hindi": "कहूँ तो कोउ न मानई, सहूँ तो जिया जाय ।", "explanation": "If I speak, no one believes. If I remain silent, my soul suffers.", "translation": "Speak and none believe. Silent, the soul suffers."},
        {"couplet_hindi": "गुरु बिन ज्ञान न उपजै, गुरु बिन मिलै न मोष ।", "explanation": "Without a Guru, there is no knowledge and no salvation.", "translation": "No Guru, no wisdom, no freedom."},
        {"couplet_hindi": "माया मरी न मन मरा, मर-मर गया शरीर ।", "explanation": "Illusion didn't die, the mind didn't die; only the body died again and again.", "translation": "Illusion and mind live on; only the body dies repeatedly."},
        {"couplet_hindi": "दुर्लभ मानुष जन्म है, देह न बारम्बार ।", "explanation": "Human birth is precious and rare.", "translation": "Human life is a rare treasure."},
        {"couplet_hindi": "कबीरा खड़ा बाज़ार में, सबकी मांगे खैर ।", "explanation": "Kabir stands in the market wishing well for everyone.", "translation": "Kabir wishes peace for all in the marketplace."},
        {"couplet_hindi": "सब धरती कागद करूँ, लेखनी सब बनराय ।", "explanation": "Even if the whole earth were paper and all forests were pens...", "translation": "If the earth were paper and forests were pens..."},
        {"couplet_hindi": "सात समुद्र की मसि करूँ, गुरु गुण लिखा न जाय ॥", "explanation": "...and seven oceans were ink, the Guru's glory could not be written.", "translation": "...and oceans were ink, the Guru's glory remains unwritten."},
        {"couplet_hindi": "कबीर आपा मेटि करि, हरि भजि तजि अभिमान ।", "explanation": "Kabir, end the ego and pray without pride.", "translation": "Kabir, kill the 'I' and pray with humility."},
        {"couplet_hindi": "काल करे सो आज कर, आज करे सो अब ।", "explanation": "Do tomorrow's work today, and today's work now.", "translation": "Tomorrow's task today, today's task now."}
        {"couplet_hindi": "कबीरा यहु घर प्रेम का, खाला का घर नाहिं । सीस उतारे हाथि करि, सो पैठे घर माहिं ॥", "explanation": "This is the house of love, not your aunt's house. Only he who can offer his head (ego) can enter here.", "translation": "This is the home of love, not an easy path. Only one who sacrifices his ego can enter."},
        {"couplet_hindi": "बपु बपुरो बुड़न डरो, रहा किनारे बैठ । जिन खोजा तिन पाइया, गहरे पानी पैठ ॥", "explanation": "The fearful one sat on the shore afraid of drowning. But those who searched found the pearls by diving deep.", "translation": "The timid sat on the bank, fearing the depth. Those who searched found treasures in the deep water."},
        {"couplet_hindi": "कबीर नौबत आपणी, दिन दस लेहु बजाय । यहु पुर पटन यहु गली, बहुरि न देखहु आय ॥", "explanation": "Play your drum (live your life) for these few days. You will not see this town or these streets again.", "translation": "Live your life fully for these few days. You won't return to these streets again."},
        {"couplet_hindi": "पढ़ि पढ़ि के पत्थर भये, लिखि लिखि भये जु ईंट । कह कबीर वा प्रेम की, एको मिली न छींट ॥", "explanation": "People became like stones and bricks by reading and writing endlessly, but they never felt even a drop of true love.", "translation": "Scholars turned to stone reading books. They never felt a single drop of true love."},
        {"couplet_hindi": "कबीर तन पंछी भया, जहाँ मन तहाँ उडि जाय । जो जैसी संगति करै, सो तैसा फल खाय ॥", "explanation": "The body has become a bird that flies wherever the mind goes. One reaps the fruit based on the company they keep.", "translation": "The body is a bird flying where the mind leads. You eat the fruit of the company you keep."},
        {"couplet_hindi": "माया दीपक नर पतंग, भ्रमि भ्रमि इवैं पड़ंत । कह कबीर गुरु ज्ञान थे, एक आध उबरंत ॥", "explanation": "Worldly illusion is the lamp and man is the moth circling it until he falls. Only a few are saved by the Guru's knowledge.", "translation": "Maya is the flame and man the moth. Only through the Guru's wisdom are a few saved."},
        {"couplet_hindi": "नहाये धोये क्या भया, जो मन का मैल न जाय । मीन सदा जल में रहै, धोये बास न जाय ॥", "explanation": "What use is bathing if the filth of the mind remains? A fish lives in water forever, but its smell never leaves.", "translation": "Bathing is useless if the mind is dirty. A fish lives in water but always smells of fish."},
        {"couplet_hindi": "कबीर संगत साधु की, बेगि करीजै जाय । दुरमति दूरि गंवाइ सी, देशी सुमति बताय ॥", "explanation": "Seek the company of a saint quickly. It will drive away evil thoughts and give you a good mind.", "translation": "Seek a saint's company fast. It removes bad thoughts and brings wisdom."},
        {"couplet_hindi": "कबीरा यहु तन जात है, सकै तो लेहु बहोरि । जा घट प्रीति न राम की, सो घट गया अकारि ॥", "explanation": "This body is passing away; save it if you can. A heart without love for the Divine is a life wasted.", "translation": "This body is fading; save it with love. Without devotion, this life is in vain."},
        {"couplet_hindi": "कबीर सो धन संचिये, जो आगै को होय । सीस चढ़ाये पोटली, ले जात न देख्या कोय ॥", "explanation": "Gather that wealth which will help you in the future. No one has ever been seen carrying a bundle of money on their head after death.", "translation": "Save the wealth that lasts. No one takes worldly riches to the grave."},
        {"couplet_hindi": "कामी क्रोधी लालची, इनसे भक्ति न होय । भक्ति करे कोइ सूरमा, जाति वरन कुल खोय ॥", "explanation": "The lustful, angry, and greedy cannot perform devotion. Only a brave soul who leaves behind ego and status can truly serve.", "translation": "The greedy and angry cannot devote. Only a hero who leaves his ego can truly serve."},
        {"couplet_hindi": "पाँच पहर धंधे गया, तीन पहर गया सोय । एको घड़ी न सिमिरया, तो जम की मार क्यूं न होय ॥", "explanation": "You spent fifteen hours working and nine hours sleeping. You didn't remember God for even a moment; why shouldn't Death strike you?", "translation": "Fifteen hours working, nine sleeping. Not a moment for God; death will surely come."},
        {"couplet_hindi": "कबीर कलजुग आइया, करम कथै सब कोय । जेहि घट दया न संचरे, सो कलिहारी होय ॥", "explanation": "In this age, everyone talks of deeds. But a heart that has no compassion is truly lost in this dark age.", "translation": "In this dark age, all talk of deeds. But a heart without mercy is truly lost."},
        {"couplet_hindi": "साधु सिष तो बहुत हैं, गुरु न मिलिया कोय । कबीर चेला क्या करे, गुरु बिन ज्ञान न होय ॥", "explanation": "There are many students, but no true Guru is found. What can a disciple do? Without a Guru, there is no knowledge.", "translation": "Many students exist, but few true Gurus. Without a Guru, there is no wisdom."},
        {"couplet_hindi": "प्रेम बिना जो जप तपै, सो सब निष्फल जाय । कबीर सोई भक्त है, जाके हिरदै प्रेम समाय ॥", "explanation": "Chanting and penance without love are all fruitless. Only he is a true devotee whose heart is filled with love.", "translation": "Prayers without love are useless. A true devotee has a heart full of love."},
        {"couplet_hindi": "कबीर सोई सुरमा, जो मन सों खेलै जाय । पंच चपेटा मारि करि, मन को वश में लाय ॥", "explanation": "He is a true warrior who battles his own mind. He strikes down the five senses and brings the mind under control.", "translation": "The true hero fights his own mind. He tames the senses and wins the battle within."},
        {"couplet_hindi": "जग में रहिबे को कछू, ठौर ठिकाना नाहिं । कबीर राम नाम बिन, जम के फंदे माहिं ॥", "explanation": "There is no permanent place to stay in this world. Without the name of the Lord, you are caught in the trap of Death.", "translation": "There is no permanent home here. Without the Divine name, you are caught by death."},
        {"couplet_hindi": "कबीर कलि का रूप देखि, हंसा मन न धीर । जहाँ देखूं तहाँ पाप है, कैसे तिरै कबीर ॥", "explanation": "Seeing the state of this age, the soul has no peace. Wherever I look, there is sin; how will one cross over?", "translation": "In this dark age, the soul finds no peace. Sin is everywhere; how shall we cross the ocean of life?"},
        {"couplet_hindi": "सतगुरु हमसों रीझि करि, एक कह्या प्रसङ्ग । बरस्या बादल प्रेम का, भीजि गया सब अङ्ग ॥", "explanation": "The true Guru was pleased and told a story. It was like a cloud of love rained down and soaked every part of my being.", "translation": "The Guru spoke a word of truth. It rained love and soaked my entire soul."},
        {"couplet_hindi": "कबीर दीवा तेल बिन, बाती बिनु जरि जाय । साँझ सकारे राम कहि, कदे न बुझि जाय ॥", "explanation": "A lamp without oil and wick will die out. But if you remember the Lord day and night, your light will never extinguish.", "translation": "A lamp dies without oil. But the light of the Divine name burns forever."}
        {"couplet_hindi": "कस्तूरी कुंडली बसै, मृग ढूँढै बन माहिं । ज्यों घट-घट राम हैं, दुनिया देखै नाहिं ॥", "explanation": "The musk is in the deer's own navel, but it hunts for it in the forest. Similarly, God resides in every heart, but the world sees Him not.", "translation": "Musk is in the deer, yet it seeks it in the woods. God is in every heart, yet the world sees Him not."},
        {"couplet_hindi": "साँच बराबर तप नहीं, झूठ बराबर पाप । जाके हिरदे साँच है, ताके हिरदे आप ॥", "explanation": "There is no penance like truth, and no sin like a lie. God resides in the heart of one who holds the truth.", "translation": "No penance like truth, no sin like a lie. God dwells in the heart where truth resides."},
        {"couplet_hindi": "चलती चाकी देख के, दिया कबीरा रोय । दुइ पाटन के बीच में, साबुत बचा न कोय ॥", "explanation": "Seeing the grinding stones, Kabir cried. Between the two wheels of the world (heaven and earth/duality), nothing remains whole.", "translation": "Seeing the millstone, Kabir wept. Between the two wheels, nothing stays whole."},
        {"couplet_hindi": "मंगन मरण समान है, मति कोउ मांगो भीख । मंगन से तो मरन भला, यह सतगुरु की सीख ॥", "explanation": "Begging is like death; let no one beg. Death is better than begging; this is the teaching of the Satguru.", "translation": "To beg is to die; let no one beg. Death is better than begging; so says the Satguru."},
        {"couplet_hindi": "जब तू आया जगत में, लोग हंसे तू रोय । ऐसी करनी कर चलो, तुम हँसो जग रोय ॥", "explanation": "When you were born, others laughed while you cried. Live your life in such a way that when you leave, you laugh and the world cries.", "translation": "At birth, you cried while others laughed. Live so that at death, you laugh while others cry."},
        {"couplet_hindi": "सोना सज्जन साधु जन, टूटि जुरै सौ बार । दुर्जन कुम्भ कुम्हार के, एकै धका दरार ॥", "explanation": "Gold, good people, and saints can be broken and joined a hundred times. But the wicked are like a clay pot; one strike and they are cracked forever.", "translation": "Gold and saints join even if broken. The wicked are like clay; one crack and they are gone."},
        {"couplet_hindi": "उज्जल पहिरे कापड़ा, पान सुपारी खाय । एकै हरि के नाम बिन, बांधा जमपुर जाय ॥", "explanation": "You wear bright clothes and eat betel leaves, but without the name of the Lord, you go to the city of Death in chains.", "translation": "You wear fine clothes and feast, but without God's name, you are bound for Death's door."},
        {"couplet_hindi": "काया कांची कुंभ है, लिये फिरे था साथ । टपका लागा फूटि गया, कछू न आया हाथ ॥", "explanation": "The body is like an unbaked clay pot that you carry with pride. One drop of rain (death) and it shatters, leaving nothing in your hands.", "translation": "The body is a clay pot carried with pride. One drop and it shatters, leaving nothing behind."},
        {"couplet_hindi": "कबीरा तेरी झोंपड़ी, गलकटियन के पास । जो करेंगे सो भरेंगे, तुम क्यों भये उदास ॥", "explanation": "Kabir, your hut is near the butchers. Why be sad? Those who do wrong will reap the consequences; you need not worry.", "translation": "Kabir, your hut is near the wicked. Be not sad; they shall reap what they sow."}
        {"couplet_hindi": "धीरे-धीरे रे मना, धीरे सब कुछ होय । माली सींचे सौ घड़ा, ॠतु आए फल होय ॥", "explanation": "Slowly, oh mind, everything happens slowly. The gardener may water with a hundred pots, but fruit only comes in its season.", "translation": "Slowly my mind, slowly everything happens. The gardener waters a hundred pots, but fruit arrives only in its season."},
        {"couplet_hindi": "सांईं इतना दीजिये, जा मे कुटुम समाय । मैं भी भूखा न रहूँ, साधु ना भूखा जाय ॥", "explanation": "Oh God, give me only enough to feed my family. So I do not go hungry, and no guest goes hungry from my door.", "translation": "Lord, give me only this much, that my family is sustained. I shouldn't remain hungry, nor should a saint go hungry."},
        {"couplet_hindi": "निंदक नियरे राखिए, ऑंगन कुटी छवाय । बिन पानी, साबुन बिना, निर्मल करे सुभाय ॥", "explanation": "Keep your critics close, give them a hut in your yard. Without soap or water, they cleanse your character.", "translation": "Keep the critic close to you, build him a hut in your courtyard. Without water or soap, he cleanses your nature."},
        {"couplet_hindi": "कबीरा सूता क्या करे, जागी न जपे मुरार । एक दिन ऐसा सोवना, लंबे पाँव पसार ॥", "explanation": "Kabir, why do you sleep? Wake up and remember God. One day you will sleep a long sleep with your legs stretched out (death).", "translation": "Kabir, what do you do sleeping? Wake up and chant God's name. One day you must sleep like this, legs stretched far."},
        {"couplet_hindi": "जैसे तिल में तेल है, ज्यों चकमक में आग । तेरा साईं तुझ में है, तू जाग सके तो जाग ॥", "explanation": "Just as oil is inside the sesame seed, and fire is in the flint stone. Your God is inside you, wake up if you can.", "translation": "Like oil in sesame, like fire in flint. Your Lord is within you, awake if you can awake."},
        {"couplet_hindi": "जिन खोजा तिन पाइया, गहरे पानी पैठ । मैं बपुरा बूडन डरा, रहा किनारे बैठ ॥", "explanation": "Those who searched, found it by diving into deep water. I, the poor one, was afraid of drowning and sat on the shore.", "translation": "Those who searched, found it by diving deep. I, poor fellow, feared drowning, and sat on the shore."},
        {"couplet_hindi": "कबीरा खड़ा बाज़ार में, मांगे सबकी खैर । ना काहू से दोस्ती,न काहू से बैर ॥", "explanation": "Kabir stands in the market, wishing well for everyone. He has friendship with no one, and enmity with no one.", "translation": "Kabir stands in the market, praying for everyone's welfare. Neither friendship with anyone, nor enmity with anyone."}
    ]

    current_time = datetime.datetime.now(datetime.timezone.utc)
    hours_since_epoch = int(current_time.timestamp() // 3600)
    index = hours_since_epoch % len(couplets)
    doha = couplets[index]
    
    # 1. TEXT EXPORT
    text_output = f"""
====================================
           KABIR DOHA            
====================================
{doha['couplet_hindi']}

MEANING:
{doha['explanation']}

TRANSLATION:
{doha['translation']}
====================================
"""
    with open('doha.txt', 'w', encoding='utf-8') as f:
        f.write(text_output)

    # 2. RSS EXPORT
    fg = FeedGenerator()
    fg.title('Hourly Kabir Das Dohas')
    fg.link(href='https://github.com/fladka/Kabir', rel='alternate')
    fg.description('Timeless wisdom by Sant Kabir Das')
    fg.language('hi')

    for i in range(3):
        idx = (hours_since_epoch - i) % len(couplets)
        d = couplets[idx]
        fe = fg.add_entry()
        title = d.get('couplet_hindi', 'Kabir Doha')
        fe.title(title)
        fe.description(f"<p>Meaning: {d.get('explanation', '')}</p><p>Translation: {d.get('translation', '')}</p>")
        fe.id(title + str(hours_since_epoch - i))
        fe.link(href="https://github.com/fladka/Kabir")
        item_time = current_time.replace(minute=0, second=0, microsecond=0) - datetime.timedelta(hours=i)
        fe.pubDate(item_time)

    fg.rss_file('rss.xml')
    print("Hourly Text and RSS feeds generated successfully!")

if __name__ == '__main__':
    generate_kabir_feed()
